### PR TITLE
updating git submodule; closes #184

### LINKED ISSUE #184: updating git submodule
The `{tlf}` git submodule for `build-scripts` is at the following commit:

image

But the submodule repo has been updated since then:

image

How can we update the `\scripts` folder to use the latest commit?

```git
git submodule update --init --recursive
```

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
As far as I can see, the failing build is due to #220, and nothing to do with updates in this PR.

**Comment by Yuri05** [comment]
The error is "**Running examples in 'tlf-Ex.R**' failed". Where does tlf-Ex.R come from? I cannot find this file at all
```
* checking examples ... ERROR
Running examples in 'tlf-Ex.R' failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: setXAxis
> ### Title: setXAxis
> ### Aliases: setXAxis
> 
> ### ** Examples
> 
> myPlot <- addLine(x = c(1, 2, 3), y = c(10, 50, 100))
> 
> # Set x-axis in log scale
> setXAxis(myPlot, scale = Scaling$log)
> 
> # Set x-axis ticklabels to Greek letters
> setXAxis(myPlot, ticks = c(1, 2, 3), ticklabels = parse(text = c("alpha", "beta", "gamma")))
Error: Only vectors of base object types are allowed.
Execution halted
```

**Comment by IndrajeetPatil** [comment]
https://github.com/Open-Systems-Pharmacology/TLF-Library/blob/fe4eac22766ceebba3886aedf96ab2de875bf12f/R/utilities-axis.R#L48-L56

**Comment by PavelBal** [comment]
The `xxx-Ex.R` are generated on build from examples... Meaning some of the examples are failing.

**Review by pchelle — APPROVED** [review]

**Pull request merged**
