### PR TITLE
fixes #203 Add artifacts without version number to enable usage as pe…

### LINKED ISSUE #203: Add artifacts without version number to enable usage as permalink
Create additional artifacts **tlf.zip** and **tlf.tar.gz** (without the version number), so that they can e used in the permalinks to the latest built package version (s. the discussion in https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine/pull/592)

### PR DESCRIPTION
**Pull request by Yuri05**
…rmalink

### CODE REVIEW

**Comment by msevestre** [comment]
I don't think you can install such a package then. At least the zip file on Windows. I had tried before and it said the package was corrupted

**Comment by Yuri05** [comment]
>I don't think you can install such a package then. At least the zip file on Windows. I had tried before and it said the package was corrupted

I used it in the latest PR on RE - seems to work so far

**Comment by msevestre** [comment]
Can you install it locally using r studio?
I think we should also have the version with version if not

**Comment by Yuri05** [comment]
>I think we should also have the version with version if not

Yep. Now we have both artifacts: with and without the version (a **copy** of created package is created before publishing the artifacts)
grafik

**Pull request merged**
