### PR TITLE
Bump package version; update NEWS

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
@pchelle Feel free to update the NEWS later if you think I missed something important.

**Comment by Yuri05** [comment]
The version in **docs** must be updated then as well, right?

**Comment by IndrajeetPatil** [comment]
Yes, but I was going to do that in a separate PR. As you wish.

**Comment by Yuri05** [comment]
the version in AppVeyor.yml must be incremented as well
https://github.com/Open-Systems-Pharmacology/TLF-Library/blob/3613aa2b5ae67f495661360173399c2b6d7a755f/appveyor.yml#L15

**Pull request merged**
