### PR TITLE
303 obs map to shape

### PR DESCRIPTION
**Pull request by pchelle**

### CODE REVIEW

**Comment by pchelle** [comment]
@IndrajeetPatil 

Here are a few examples for integration with osp below:
<details>
<summary>Data</summary>

```r
simTime <- seq(1, 10, 0.2)
simData <- data.frame( 
  x = rep(simTime, 3),
  y = c(10 * exp(-0.5*simTime), 5*(1-exp(-simTime)), 5+cos(simTime)),
  ymin =  c(10 * exp(-0.5*simTime), 5*(1-exp(-simTime)), 5+cos(simTime)),
  ymax =  c(10 * exp(-0.5*simTime), 5*(1-exp(-simTime)), 5+cos(simTime)),
  groups = c(rep("Group 1", length(simTime)), rep("Group 2", length(simTime)), rep("Group 3", length(simTime)))
)

obsData <- data.frame(
  x = rep(c(0, 1, 2, 3, 4), 4),
  y = sample.int(20, 20), 
  groups = c(rep("Group 1", 10), rep("Group 2", 6), rep("Group 3", 4)), 
  names = c(rep("G101", 4),  rep("G102", 3) ,rep("G103", 3),
           rep("G201", 3), rep("G202", 3),  rep("G301", 4))
)
```

</details>

<details>
<summary>Observed data only </summary>

```r
plotTimeProfile(
  observedData = obsData,
  observedDataMapping = ObservedDataMapping$new(
    x="x",y="y",shape="names",color="groups")
  )
```

tp1

You can easily turn off the legend guide of shape only with `{ggplot2}`

```r
plotTimeProfile(
  observedData = obsData,
  observedDataMapping = ObservedDataMapping$new(
    x="x",y="y",group="groups")
  )
```

tp2


</details>

<details>
<summary>With simulated data</summary>

```r
plotObject = plotTimeProfile(
    data = simData,
    dataMapping = TimeProfileDataMapping$new(
      x="x",y="y",group="groups"
    ),
    observedData = obsData,
    observedDataMapping = ObservedDataMapping$new(
      x="x",y="y",shape="names",color="groups")
  )
```

tp3

```r
plotObject = plotTimeProfile(
    data = simData,
    dataMapping = TimeProfileDataMapping$new(
      x="x",y="y",group="groups"
    ),
    observedData = obsData,
    observedDataMapping = ObservedDataMapping$new(
      x="x",y="y",group="groups")
  )
```

tp4

</details>

<details>
<summary>With population simulated data</summary>

```r
plotObject = plotTimeProfile(
    data = simData,
    dataMapping = TimeProfileDataMapping$new(
      x="x",y="y",group="groups"#,ymin="ymin",ymax="ymax"
    ),
    observedData = obsData,
    observedDataMapping = ObservedDataMapping$new(
      x="x",y="y",shape="names",color="groups")
  )
```
tp5


```r
plotObject = plotTimeProfile(
    data = simData,
    dataMapping = TimeProfileDataMapping$new(
      x="x",y="y",group="groups"#,ymin="ymin",ymax="ymax"
    ),
    observedData = obsData,
    observedDataMapping = ObservedDataMapping$new(
      x="x",y="y",group="groups")
  )
```

tp6

</details>

**Comment by IndrajeetPatil** [comment]
Thanks, Pierre! Trying it out now.

The build failure is spurious; you can ignore it for now.

**Comment by IndrajeetPatil** [comment]
Should I try with this PR or with #352?

AFAICT, they are identical.

**Comment by pchelle** [comment]
> Should I try with this PR or with #352?
> 
> AFAICT, they are identical.

Yes, I thought that my may be not up-to-date develop branch was reason for covr not to work
I will delete the other PR

**Comment by IndrajeetPatil** [comment]
Am I doing something wrong here? This [issue](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/982#issuecomment-1188759745) still persists. 

``` r
library(tlf)

df <- dplyr::tibble(
  xValues = c(0, 1, 2, 3, 4, 0, 1, 2, 3, 4),
  yValues = c(
    0,
    0.00788349099457264, 0.0343151688575745, 0.0759411081671715,
    0.130162701010704, 0, 5.10453501689767e-09, 4.76278302130595e-07,
    6.20401988271624e-06, 3.64091392839327e-05
  ), 
  group = "myGroup", 
  name = c(rep("data1", 5),  rep("data2", 5))
)

tlf::plotTimeProfile(
  data = as.data.frame(df),
  dataMapping = tlf::TimeProfileDataMapping$new(
    x = "xValues",
    y = "yValues",
    group = "group"
  ),
  plotConfiguration = TimeProfilePlotConfiguration$new()
)
```



<sup>Created on 2022-07-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by pchelle** [comment]
> Am I doing something wrong here? This [issue](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/982#issuecomment-1188759745) still persists.

Yes, it is also in #340 ,
The problem seems that you map all the simulations to the same group `"myGroup"` so all the simulations are connected
Same as the observed data, you would need to de-correlate `group` and `name` in the dataMapping.

```r
tlf::plotTimeProfile(
  data = as.data.frame(df),
  dataMapping = tlf::TimeProfileDataMapping$new(
    x = "xValues",
    y = "yValues",
    color = "group",
    linetype = "name"
  ),
  plotConfiguration = TimeProfilePlotConfiguration$new()
)
```

tp1

**Comment by IndrajeetPatil** [comment]
Also, when only observed datasets are present, the legend for shape mappings should not be present.

I know that the resulting graph would be confusing to read, but this is what has been specified [here](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/980#issuecomment-1192726622).

``` r
library(ospsuite)
#> Loading required package: rClr
#> Loading the dynamic library for Microsoft .NET runtime...
#> Loaded Common Language Runtime version 4.0.30319.42000

dataSet1 <- DataSet$new(name = "Dataset1")
dataSet1$setValues(1, 1)
dataSet1$yDimension <- ospDimensions$`Concentration (molar)`
dataSet1$molWeight <- 1

dataSet2 <- DataSet$new(name = "Dataset2")
dataSet2$setValues(2, 1)
dataSet2$yDimension <- ospDimensions$`Concentration (mass)`
dataSet2$molWeight <- 1

dataSet3 <- DataSet$new(name = "Dataset3")
dataSet3$setValues(1, 3)
dataSet3$yDimension <- ospDimensions$`Concentration (mass)`
dataSet3$molWeight <- 1

myCombDat <- DataCombined$new()
myCombDat$addDataSets(
  c(dataSet1, dataSet2, dataSet3),
  groups = c("myGroup", "myGroup", "myGroup")
)

plotIndividualTimeProfile(myCombDat)
#> Warning: Removed 3 rows containing missing values (geom_segment).
#> Removed 3 rows containing missing values (geom_segment).
```



<sup>Created on 2022-07-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

So the expected output is the following:

eg

**Comment by pchelle** [comment]
Or if you want to display the name instead of group:

```r
tlf::plotTimeProfile(
  data = as.data.frame(df),
  dataMapping = tlf::TimeProfileDataMapping$new(
    x = "xValues",
    y = "yValues",
    group = "name"
  ),
  plotConfiguration = TimeProfilePlotConfiguration$new()
)
```

tp1

**Comment by IndrajeetPatil** [comment]
Works great! Thanks.

Also, as mentioned [here](https://github.com/Open-Systems-Pharmacology/TLF-Library/pull/351#issuecomment-1199042627), the legend for linetype mapping should be suppressed:

``` r
library(tlf)

df <- dplyr::tibble(
  xValues = c(0, 1, 2, 3, 4, 0, 1, 2, 3, 4),
  yValues = c(
    0,
    0.00788349099457264, 0.0343151688575745, 0.0759411081671715,
    0.130162701010704, 0, 5.10453501689767e-09, 4.76278302130595e-07,
    6.20401988271624e-06, 3.64091392839327e-05
  ), 
  group = "myGroup", 
  name = c(rep("data1", 5),  rep("data2", 5))
)

tlf::plotTimeProfile(
  data = as.data.frame(df),
  dataMapping = tlf::TimeProfileDataMapping$new(
    x = "xValues",
    y = "yValues",
    color = "group",
    linetype = "name"
  ),
  plotConfiguration = TimeProfilePlotConfiguration$new()
)
```



<sup>Created on 2022-07-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by pchelle** [comment]
> Also, when only observed datasets are present, the legend for shape mappings should not be present

I think it is better to keep it this way in `tlf` (so users can decide what they prefer if they are using tlf directly).
And we can hide it internally in `ospsuite` with `{ggplot2}`.
Below is the line of code to hide the legend
- if observed data only, use `timeProfilePlot + ggplot2::guides(shape = "none")`
- if simulated data only, use `timeProfilePlot + ggplot2::guides(linetype = "none")`

Thoughts ?

**Comment by IndrajeetPatil** [comment]
I think that's reasonable. _tlf_ defaults are what I'd expect!

**Review by IndrajeetPatil — APPROVED** [review]

**Pull request merged**
