### PR TITLE
Fixes #206 restore vignette image files

### LINKED ISSUE #206: vignette broken image links
@IndrajeetPatil 
Image links of vignettes [plot-maker](https://www.open-systems-pharmacology.org/TLF-Library/articles/plot-maker.html) and [theme-maker](https://www.open-systems-pharmacology.org/TLF-Library/articles/theme-maker.html) do not seem to work

Is it from the documentation build or do I need to locate and call the images from `inst/extdata` ?

### PR DESCRIPTION
**Pull request by pchelle**
Fix suggested from https://github.com/r-lib/pkgdown/issues/1231

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
Nice! Thanks for taking care of this.

**Comment by pchelle** [comment]
> Nice! Thanks for taking care of this.

I am not sure this will work though. In case I found this as backup plan (but I still lack experience with github actions):
https://github.com/ArgoCanada/argoFloats/issues/172

**Comment by Yuri05** [comment]
I hope the page will be displayed black on white background and not white on black background? 😉

**Comment by pchelle** [comment]
> I hope the page will be displayed black on white background and not white on black background? 😉

Should be good for `{tlf}`, there is still some black theming in the reporting engine documentation though.
Comparing the `_pkgdown.yml` files with the other packages, there is still some `theme: arrow-dark` and among other things

**Pull request merged**
